spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          paymentClient:
            read-timeout: 30000
            connect-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: beans

toss:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  url: https://api.tosspayments.com

security:
  jwt:
    secret-key: hogihogihogihogihogihogihogihogihogihogiHOGIhogihogihogihogi
    expiration-time: 36000000000000
